### ISSUE TITLE
环境应该已经搭好了，然后出现了这种错误（以及木偶启动不动），不知道是否可以解答一下

### ISSUE THREAD

**Issue by Amuletter** [bigbrother666sh/shezhangbujianle#6]
2022-05-08 00:05:06,883 - PuppetService - INFO - init puppet ...
2022-05-08 00:05:06,884 - PuppetService - INFO - starting the puppet ...
2022-05-08 00:06:23,510 - Wechaty - ERROR - The network is not good, the bot will try to restart after 60 seconds.
But here are some suggestions for you:
* 查看token是否可用？（过期或协议不可用）
* docker 服务是否正常启动？
* python-wechaty bot 是否正常启动？
* python-wechaty bot 是否能ping通docker服务？
* 由于版本细节问题，目前python-wechaty 支持最好的wechaty镜像为：[wechaty/wechaty:0.65](https://hub.docker.com/layers/wechaty/wechaty
/0.65/images/sha256-d39b9fb5dece3a8ffa88b80a8ccfd916be14b9d0de72115732c3ee714b0d6a96?context=explore)

I suggest that you should follow the template code from: https://wechaty.readthedocs.io/zh_CN/latest/ to avoid the unnecessary bugs.

2022-05-08 00:07:23,511 - Wechaty - INFO - restarting the bot ...
2022-05-08 00:07:23,511 - Wechaty - INFO - wechaty is stopping ...
2022-05-08 00:07:23,511 - PuppetService - INFO - stop()

00:12:50 SILL Io ioMessage() is a nop function before be overwritten from cloud
00:12:50 WARN Message listener() payload.listenerId should be set! See: https://github.com/wechaty/puppet/issues/187
Puppet: wechaty-puppet@1.10.27
Error
    at WechatifiedUserClass.listener (file:///C:/Users/Amulet/AppData/Roaming/npm/node_modules/wechaty/dist/esm/src/user-modules/message.js:254:27)
    at PuppetXp.<anonymous> (file:///C:/Users/Amulet/AppData/Roaming/npm/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:221:54)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
00:12:50 SILL PuppetLoginMixin get currentUserId()
00:12:51 SILL Io start() setInterval() ws.ping()
00:13:01 SILL Io start() setInterval() ws.ping()
00:13:11 SILL Io start() setInterval() ws.ping()
00:13:21 SILL Io start() setInterval() ws.ping()

Error: connect ETIMEDOUT 172.67.139.224:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.67.139.224',
  port: 443
}
00:16:22 VERB Io initWebSocket()
00:16:43 WARN Io wsOnError() error event[connect ETIMEDOUT 172.67.139.224:443]
00:16:43 ERR Io wsOnError() ws.on(error) ws.readyState is CLOSING: connect ETIMEDOUT 172.67.139.224:443
00:16:43 SILL StateSwitch <Io> active() is true
00:16:43 WARN Io wsOnClose() close event[1006: ]
00:16:43 VERB Io reconnect()
00:16:43 SILL StateSwitch <Io> inactive() is false
00:16:43 WARN Io reconnect() will reconnect after 0 s
Error: connect ETIMEDOUT 172.67.139.224:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.67.139.224',
  port: 443
}

**Comment by bigbrother666sh** [comment]
您用的是那个puppet？

**Comment by Amuletter** [comment]
> 你用的是那个木偶？

是按照 安装说明使用的puppt
